FROM debian

RUN apt-get update && apt-get install -y apache2 apt-get clean

ENV APACHE_LOCK_DIR="/var/Lock"
ENV APACHE_PID_FILE="/var/run/apache2.pid"
ENV APACHE RUN USER="www-data"
ENV APACHE RUN GROUP="www-data"
ENV APACHE_LOG_DIR="/var/log/apache2"

LABEL description="Webserver"

VOLUME /var/www/html/ EXPOSE 80
